services:
  frontendserver:
    build:
      context: .  
      dockerfile: docker/httpd_server_file
    image: apache-server  # Use your specified image
    container_name: frontend-running  # Set the container name
    ports:
      - "${APACHE_IPV6}:80:80"  # Bind the specified IPv6 address and port
      - "${APACHE_IPV6}:443:443"  # Bind the specified IPv6 address and port
    depends_on:
      - backendserver  # Ensure Apache waits for MariaDB container
    networks:
      - frontend_network
  
  backendserver:
    build:
      context: .
      dockerfile: docker/node_backend_server_file
    image: nodejs-server
    container_name: backend-running  # Set a custom name for the container
    environment:
      - MARIADB_HOST=mariadbserver
      - MARIADB_PORT=3306
      - MONGODB_HOST=mongodbserver
      - MONGODB_PORT=27017
    ports:
      - "8080:8080"
    volumes:
      - /var/www/private/nodejs/userdata:/var/www/private/nodejs/  # Mount the volume
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - mariadbserver
      - mongodbserver
    
  mongodbserver:
    image: mongo:6.0.17
    container_name: mongodb-server
    env_file:
      - /var/www/private/nodejs/rootdata/.env.mongo.internals
    ports:
      - "27017:27017"
    networks:
      - backend_network

  mariadbserver:
    image: mariadb:11.5.2
    container_name: mariadb-server
    env_file:
      - /var/www/private/nodejs/rootdata/.env.sql.internals
    ports:
      - "3306:3306"
    networks:
      - backend_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
